// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfjydtygaymoovkkmyuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmanlkdHlnYXltb292a2tteXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTk5MDksImV4cCI6MjA1OTQzNTkwOX0.WCbKoyxScT-pOYT1f8ItXpflOKYYc61KYhLKtbUvgr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);